### ISSUE TITLE
Question: build does not include some feature

### ISSUE THREAD

**Issue by doc75** [magnetikonline/dockerkeepassxdeb#1]
Hello,

I tried your repo to create an image to be installed on 16.04.
Build and install are OK, but I see 2 strange things:
1. autotype is not present
2. search icon is showing a screen instead of the magnifying glass

Do you have the same behavior or do I do something wrong ?
I searched on the keepassx site, but I did not see build option to activate the autotype.

**Comment by magnetikonline** [comment]
To be honest - for Ubuntu 16.04LTS KeepassX 2.0.2 is already available - so I have been using that instead. Have you tried just:

``` sh
$ apt install keepassx
```

See if that gives everything you need? Will probably only go back to this Dockerfile is a new version of KeepassX is released - but is not added to Ubuntu's 16.04 repositories...

  Pete

**Comment by doc75** [comment]
Actually I am using the version from Ubuntu official repo, but I have some issues with autofill not working properly. I was therefore trying to build the master version to see if it was solving the issue (but it does not have the autofill activated at all ;-( )

**Comment by magnetikonline** [comment]
Not a problem @doc75 - I'll close this one out. Maybe ask the questions over at the KeepassX forums direct?
